image: $IMAGE

stages:
    - test
    - build
    - deploy

test:
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y -qq
          python3-all-dev python-virtualenv
    script:
        - make test
        - make docs
    artifacts:
        paths:
            - demo.html

build:sdist:
    stage: build
    before_script:
        - apt-get update -qq && apt-get install -y -qq
          python3-all-dev python-virtualenv
    script:
        - make sdist
    artifacts:
        paths:
            - dist/*.tar.gz

deploy:pypi:
    stage: deploy
    before_script:
        - apt-get update -qq && apt-get install -y -qq
          python3-all-dev python-virtualenv
    script:
        - make pypi_build/bin/activate
        - source pypi_build/bin/activate
        - twine upload dist/*.tar.gz
    only:
        - tags
        
deploy:trigger:
    stage: deploy
    trigger: epi2melabs/nanolabs
    only:
        - tags